POST http://localhost:8081/hotels
Content-Type: application/json

{
    "name" : "Hayat",
    "address" : "Kathmandy",
    "number" : "2313123"
}

###
GET  http://localhost:8081/hotels?page=1&limit=10

###
GET  http://localhost:8081/hotels/5f0d75c3e66d862748415de1

###

DELETE  http://localhost:8081/hotels/5f0d75c3e66d862748415de1

###


PATCH  http://localhost:8081/hotels/5f0d75c3e66d862748415de1
Content-Type: application/json

{
    "name" : "Everest"
}


###

GET http://localhost:8081/users/5f3f8194094775c700c50d36

###

POST http://localhost:8081/users/login
Content-Type: application/json

{
    "email" : "raheem@gmail.com",
    "password" : "raheem"
}


###
GET http://localhost:8081/users/5f536039377e2514f22fd13e

###
POST http://localhost:8081/bookings
Content-Type: application/json

{
    "user" : "5f48c7b47c37676d24989fb7",
    "hotel": "5f48c8087c37676d24989fb8",
    "bookFrom" : "December",
    "bookTo": "adsfadfa",
    "contact": "23423424",
    "numberOfRooms" : "3"
}

###
GET http://localhost:8081/bookings


###
DELETE http://localhost:8081/bookings/5f659fc426bcdb0004b73b1c


###
DELETE http://localhost:8081/users/5f3e0825e397c9e94bd32698


###
DELETE  http://localhost:8081/bookings/5f53626dbf2fa579558175f3